/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.PacienteController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Paciente;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author evellynsantospinto
 */
public class TelaPaciente extends javax.swing.JFrame {
    PacienteController pacienteController = new PacienteController();
    private final DefaultTableModel tabela;
    
    public void atualizaTabela(){
        tabela.setRowCount(0); 
        ArrayList<Paciente> lista = pacienteController.listar();
        if(lista.size()>0){
                for (Paciente p : lista) {
                tabela.addRow(new Object[]{p.getIdPaciente(), p.getNomePaciente(), p.getCpf(), p.getTelefone()});
                }
            }
    }
    /**
     * Creates new form TelaPaciente
     */
    public TelaPaciente() {
        initComponents();
        tabela = (DefaultTableModel) TabelaPaciente.getModel();
        atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getModel = new javax.swing.JPanel();
        txtNome = new javax.swing.JLabel();
        txtCpf = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JLabel();
        insereNome = new javax.swing.JTextField();
        insereCPF = new javax.swing.JTextField();
        insereTelefone = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaPaciente = new javax.swing.JTable();
        btAlterar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNome.setText("NOME:");

        txtCpf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCpf.setText("CPF:");

        txtTelefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTelefone.setText("TELEFONE:");

        insereNome.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        insereNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insereNomeActionPerformed(evt);
            }
        });

        insereCPF.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        insereCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insereCPFActionPerformed(evt);
            }
        });

        insereTelefone.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        insereTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insereTelefoneActionPerformed(evt);
            }
        });

        btCadastrar.setText("CADASTRAR");

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("CADASTRO DO PACIENTE");

        btRemover.setText("REMOVER");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        TabelaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "CPF", "TELEFONE"
            }
        ));
        jScrollPane1.setViewportView(TabelaPaciente);

        btAlterar.setText("ALTERAR");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btVoltar.setText("VOLTAR");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btAtualizar.setText("ATUALIZAR");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout getModelLayout = new javax.swing.GroupLayout(getModel);
        getModel.setLayout(getModelLayout);
        getModelLayout.setHorizontalGroup(
            getModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getModelLayout.createSequentialGroup()
                .addGroup(getModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(getModelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btVoltar))
                    .addGroup(getModelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(getModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(getModelLayout.createSequentialGroup()
                                .addGroup(getModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(getModelLayout.createSequentialGroup()
                                        .addComponent(txtTelefone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(insereTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(getModelLayout.createSequentialGroup()
                                        .addGroup(getModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCpf)
                                            .addComponent(txtNome))
                                        .addGap(29, 29, 29)
                                        .addGroup(getModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(insereNome, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(insereCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(29, 29, 29))))
                    .addGroup(getModelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAtualizar))
                    .addGroup(getModelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getModelLayout.setVerticalGroup(
            getModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getModelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(getModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNome)
                    .addComponent(insereNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(getModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insereCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf))
                .addGap(6, 6, 6)
                .addGroup(getModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insereTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(getModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btAlterar)
                    .addComponent(btRemover)
                    .addComponent(btAtualizar))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(getModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insereNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insereNomeActionPerformed
        // TODO add your handling code here:
        insereNome.requestFocus();
    }//GEN-LAST:event_insereNomeActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
    int linha = TabelaPaciente.getSelectedRow();
        if (linha != -1){
            try{
                
                // O ID continua o mesmo
                int idPaciente = (int) TabelaPaciente.getValueAt(linha, 0);
                // Novos valores
                String novoNomePaciente = insereNome.getText();
                String novoCpf = insereCPF.getText();
                String novoTelefone = insereTelefone.getText();
                
                // Verificar se todos os campos foram preenchidos
                boolean erro = false;
                if(insereNome.getText().isEmpty() ||
                   insereCPF.getText().isEmpty() ||
                   insereTelefone.getText().isEmpty()){
                    erro = true;
                }
                
                // Prosseguir com o registro
                if(!erro){
                    pacienteController.atualizar(idPaciente, novoNomePaciente, novoCpf, novoTelefone);
                    atualizaTabela();
                }
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Erro - Selecione uma linha da tabela para atualizar o registro.");
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        // TODO add your handling code here:
        int linha = TabelaPaciente.getSelectedRow();
        if (linha != -1){
            try{
                // ID
                int id = (int) TabelaPaciente.getValueAt(linha, 0);
                // Exibe a caixa de diálogo com as opções "Sim" e "Não"
                int resposta = JOptionPane.showConfirmDialog(
                null, 
                "Você deseja remover o registro do paciente selecionado?", 
                "Remover registro de paciente",               
                JOptionPane.YES_NO_OPTION  
                );

                // Verifica a resposta do usuário
                if (resposta == JOptionPane.YES_OPTION) {
                    pacienteController.remover(id);
                    atualizaTabela();
                    JOptionPane.showMessageDialog(null, "O registro do paciente foi removido com sucesso.");
                }
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Erro - Selecione uma linha da tabela para apagar o registro.");
        }
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
        TelaLogin v = new TelaLogin();
        v.setVisible(true);
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        String nomePaciente = insereNome.getText();
        String cpf = insereCPF.getText();
        String telefone = insereTelefone.getText();

    if (nomePaciente.isEmpty() || cpf.isEmpty() || telefone.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos.");
    } else {
        boolean sucesso = pacienteController.cadastrar(nomePaciente, cpf, telefone);

        if (sucesso) {
            JOptionPane.showMessageDialog(null, "Paciente cadastrado com sucesso!");
            atualizaTabela(); // atualiza JTable com os novos dados

        } else {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar paciente.");
            }
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void tabPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPacientesMouseClicked
        // TODO add your handling code here:
        int linha = TabelaPaciente.getSelectedRow();
        if (linha != -1) {
            String novoNome = (String) TabelaPaciente.getValueAt(linha, 1);
            String novoCPF = (String) TabelaPaciente.getValueAt(linha, 2);
            String novoTelefone = (String) TabelaPaciente.getValueAt(linha, 3);
            insereNome.setText(novoNome);
            insereCPF.setText(novoCPF);
            insereTelefone.setText(novoTelefone);
        }
    }//GEN-LAST:event_tabPacientesMouseClicked

    private void insereCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insereCPFActionPerformed
        // TODO add your handling code here:
       insereCPF.requestFocus();
    }//GEN-LAST:event_insereCPFActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        // TODO add your handling code here:
        atualizaTabela();
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void insereTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insereTelefoneActionPerformed
        // TODO add your handling code here:
        insereTelefone.requestFocus();
    }//GEN-LAST:event_insereTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaPaciente;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btVoltar;
    private javax.swing.JPanel getModel;
    private javax.swing.JTextField insereCPF;
    private javax.swing.JTextField insereNome;
    private javax.swing.JTextField insereTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtCpf;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtTelefone;
    // End of variables declaration//GEN-END:variables
}
